url: "https://www.didiksetiawan.com"
baseurl: ""
title: Didik Setiawan
about: Let the bits speak
description: Didik Setiawan's Blog
author: Didik Setiawan
logo: /static/img/avatar.png
category_dir: category
permalink: /blog/:year/:month/:day/:title/
allowsearch: true
timezone: Asia/Jakarta

disqus_shortname: didiksetiawan
google_analytics: UA-78151571-1

share:
  twitter_username: didik_swn
  fb_appid: 000000000000

#enableTags: true
#tagarray: []

paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-redirect-from

exclude:
  - vendor
